import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import Tools from "../components/tools/tools";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Tools />
    </>
  );
}
