import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Tools from '../components/tools/tools'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        <Header/>
        <Tools/>

     

<Image  placeholder="blur" src="https://res.cloudinary.com/dcqiq1pu5/image/upload/v1626277693/tools/Bitbucket.svg" alt="Picture of the author" layout="responsive" width={700}
      height={475} />
          </>
  )
}
